export const INTRO_STRING =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.";

// About screen
export const ABOUT_ARTIST_TITLE = "About the Artist";
export const ABOUT_ARTIST_TEXT = "Lady Elliot began her post-university career as an aerospace engineer at the Boeing Company, through which she learned that she did not fit into the typical engineer-shaped mold and that her soul was not fully fulfilled through this form of innovation alone. Her art comes from the visions, ideas, dreams and stories she sees in her imagination that she wanted to share with other others so they could see the things she sees, exactly the way she envisioned them. Through her eclectic and unique artistic style she hopes that she can bring inspiration to others to lead their own special path, tuned to their own unique frequencies. Never be afraid of the dark.";
export const ABOUT_ART_TITLE = "About the Art";
export const ABOUT_ART_TEXT_1 = "My artistic style has developed from a mixture of influences from my personal evolution as well as my fondness for the life and excitement of the night. When I first began to paint black backgrounds it was because I felt that the blackness has so much more potential and mystery to it than any other colour. White backgrounds always felt like an empty container void of mystery and excitement whereas the darkness spoke to me, as if all the characters hiding in the blackness were inviting me to come and discover them. I have always been a night owl and I do my best work at night. I first began to pair black backgrounds with brightly colors characters and creatures as a means to connect with my long lost child-self who would always insist on embodying the spirit of bright and bizarrely colored creatures. I would tell myself “today I am a purple cheetah with teal spots” and would then spend my day connecting with the essence of such a creature and fill my sketch books with the adventures of a purple cheetah.";
export const ABOUT_ART_TEXT_2 = "I felt that as I aged I was forced to conform to the cookie-cutter shape of a successful adult. After graduating college I felt depressed and separated from myself. I began to search for the solution to my unhappiness and believed the key was to access the uninhibited creativity from my childhood imagination. Painting first became a hobby and therapeutic tool to express what my rational mind did not know words for and it helped me regain access to my inner child. From this space I began the process of realigning my personal values to what made me happy instead of following the rules that American culture told me should make me happy (but did not). In this sense, the first collections I painted were deeply personal. Each piece that I worked on has its own story behind it and its own connection to my journey to express my true self.";
export const ABOUT_ART_TEXT_3 = "As the black-and-bold colors style evolved, I have found that painting is now about the expression of imagination. Each and every painting presents its own unique challenge and has its own personality. Some of my characters are not finished with their story after just one painting they even share their own ideas and secrets for their future with me. As they come to life, they share their stories with me and we discuss their future plans for this world. Each painting reminds me to celebrate the uniqueness of all of the characters that present themselves to me and it makes me very happy to share their stories with you!";